name: heartandhead
favicon: null
layout_spectrum: 0.5202358276583254
typography_spectrum: 0.22974514518864453
title: 'Heart & Head'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f5911f'
    - '#572500'
    - '#42c4de'
    - '#907058'
  brandStrength: 0.11697515891864896
  lightness: 0.5277141192927957
  saturation: 0.8767381622456014
  rhythmicContrast: 0.5292253084480762
purpose: []
